name: Get Newest Artifact

description: 'Get artifacts from the last success run of a specified workflow'

inputs:
  workflow:
    description: 'Workflow filename'
    required: true
  repository:
    description: 'Repository name with owner'
    default: ${{ github.repository }}
  artifact:
    description: 'Artifacts that match glob pattern'
    required: true
  path:
    description: 'The directory to download artifacts into (default ".")'
    default: '.'


runs:
  using: 'composite'
  steps:
    - name: Download Latest Successful Build Artifact
      run: |
        newest_success=$(gh run list -R ${{ inputs.repository }} -w ${{ inputs.workflow }} \ 
          --json conclusion,headBranch,databaseId \
          --jq 'first(.[] | select(.conclusion | contains("success"))) | .databaseId')
        [ -z "$newest_success" ] && echo "No successful run found" && exit 1 || true
        gh run download $newest_success -p ${{ inputs.artifact }} -D ${{ inputs.path }}
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      shell: bash