name: AKTIN Build Debian

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        default: 'debian-package'
        type: string
      package-name:
        description: 'Name of the debian package (either aktin-notaufnahme-i2b2 or aktin-notaufnahme-dwh)'
        required: true
        type: string


jobs:
  debian-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/debian
    steps:
      - name: Prepare Version Variable - Deployment
        if: startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Prepare Version Variable - Testing
        if: ! startsWith(github.ref, 'refs/tags/v')
        run: echo "VERSION=0-$GITHUB_REF_NAME" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Generate Cache Name
        run: echo "CACHE=${sort versions | awk '!/(^[[:space:]]*$|PACKAGE_VERSION=|#)/' ORS='--'}" >> $GITHUB_ENV

      - name: Retrieve Cached Downloads
        uses: actions/cache@v4
        with:
          path: src/downloads/
          key: downloads--${{ env.CACHE }}

      - name: Build Debian
        run: build.sh

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: build/${{ inputs.package-name }}_$VERSION.deb