name: AKTIN Deploy Debian Package

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        default: 'debian-package'
        type: string
      codename:
        description: 'OS codename'
        default: 'jammy'
        type: string
      package-name:
        description: 'Name of the debian package'
        required: true
        type: string
      package-version:
        description: 'Version of the debian package'
        required: true
        type: string
    secrets:
      SSH_USER:
        description: 'Username for the server hosting the AKTIN APT repository'
        required: true
      SSH_PRIVATE_KEY:
        description: 'Private Key for authenticating with the server hosting the AKTIN APT repository'
        required: true
      SSH_REMOTE:
        description: 'Hostname of the server hosting the AKTIN APT repository'
        required: true

jobs:
  debian-deploy:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    env:
      REPREPRO_HOME: /software/repo/org/apt   # local directory containing conf, db, dists, and pool directories
      PACKAGE: "${{ inputs.package-name }}_${{ inputs.package-version }}.deb"
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}

      - name: Setup SSH Key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Debian Package
        run: scp $PACKAGE "${{ secrets.SSH_USER }}@${{ secrets.SSH_REMOTE }}:$REPREPRO_HOME/"

      - name: Import Debian Packages
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_REMOTE }} "reprepro -b '$REPREPRO_HOME' includedeb ${{ inputs.codename }} $PACKAGE"
