name: AKTIN Build Docker

on:
  workflow_call:
    inputs:
      artifact-name:
        description: 'Artifact name'
        default: 'dockerfiles'
        type: string
      download-i2b2:
        description: 'Download i2b2 update ZIP when building notaufnahme-i2b2 docker image'
        default: false
        type: boolean


jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/docker
    steps:
      - uses: actions/checkout@v4

      - name: Generate Cache Name
        run: echo "CACHE=${sort versions | awk '!/(^[[:space:]]*$|PACKAGE_VERSION=)/' ORS='--'}" >> $GITHUB_ENV

      - name: Retrieve Cached Downloads
        uses: actions/cache@v4
        with:
          path: src/downloads/
          key: downloads--${{ env.CACHE }}

      - name: Retrieve i2b2 Update
        if: steps.i2b2-cache.outputs.cache-hit != 'true' && inputs.download-i2b2
        run:  # TODO

      - name: Build Dockerfiles
        run: build.sh

#      - name: Install
#        run: |
#          docker compose build
#          docker compose -f sample/docker-compose.yml up -d
#
#      - name: Test
#        run:  # TODO

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: |
            database/
            httpd/
            wildfly/