name: AKTIN Build & Deploy Maven

on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version number'
        required: true
        type: number
      java-distribution:
        description: 'Java distribution'
        default: 'temurin'
        required: false
        type: string
      apt-dependencies:
        description: 'Dependencies installed via apt (as space separated list)'
        required: false
        type: string
    secrets:
      AKTIN_MAVEN_USERNAME:
        description: 'Maven repository username'
        required: false
      AKTIN_MAVEN_PASSPHRASE:
        description: 'Maven repository passphrase'
        required: false
      AKTIN_MAVEN_GPG_PASSPHRASE:
        description: 'Passphrase for the maven repositories GPG private key'
        required: false
      AKTIN_MAVEN_GPG_PRIVATE_KEY:
        description: 'Content of the maven repositories GPG private key'
        required: false
      AKTIN_MAVEN_REPOSITORY:
        description: 'Hostname of the server hosting the maven repository'
        required: false


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Working Directory Variable
        run: echo "WORK_DIR=${GITHUB_REPOSITORY#aktin/}" >> $GITHUB_ENV

      - name: Checkout parent POM
        uses: actions/checkout@v4
        with:
          repository: aktin/aktin

      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: ${{ env.WORK_DIR }}

      - name: Set up JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}
          cache: maven
          server-id: aktinupload.software.magdeburg  # value of the distributionManagement/repository/id field of the pom.xml
          server-username: MAVEN_USERNAME  # env variable for username in deploy
          server-password: MAVEN_PASSPHRASE  # env variable for token/password in deploy
          gpg-private-key: ${{ secrets.AKTIN_MAVEN_GPG_PRIVATE_KEY }}  # value of the GPG private key to import
          gpg-passphrase: MAVEN_GPG_PASSPHRASE  # env variable for GPG private key passphrase

      - name: Install APT Dependencies
        if: inputs.apt-dependencies
        run: sudo apt install -y ${{ inputs.apt-dependencies }}

      - name: Build & (Unit-)Test
#        run: mvn -B package -Dchangelist=-SNAPSHOT+${{ github.run_number }}
        run: mvn -B package
        working-directory: ${{ env.WORK_DIR }}

      - name: Deploy
        if: startsWith(github.ref, 'refs/tags/v')
#        run: mvn deploy -Drevision=${GITHUB_REF_NAME#v} -Dchangelist=
        run: |
          mvn versions:set -DnewVersion=${GITHUB_REF_NAME#v}
          mvn deploy
        working-directory: ${{ env.WORK_DIR }}
        env:
          MAVEN_USERNAME: ${{ secrets.AKTIN_MAVEN_USERNAME }}
          MAVEN_PASSPHRASE: ${{ secrets.AKTIN_MAVEN_PASSPHRASE }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.AKTIN_MAVEN_GPG_PASSPHRASE }}
          MAVEN_REPOSITORY: ${{ secrets.AKTIN_MAVEN_REPOSITORY }}